fail_fast: false
default_language_version:
  python: python3
default_stages:
  - commit
  - push
minimum_pre_commit_version: 2.9.3
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies: [numpy>=1.23]
        exclude: docs
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        additional_dependencies: [toml]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-ast
      - id: check-symlinks
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: fix-encoding-pragma
        args: [--remove]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
        exclude: ^.bumpversion.cfg$
      - id: name-tests-test
        args: [--django]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-yaml
      - id: check-toml
      - id: requirements-txt-fixer
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.269
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
